<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-13T08:37:18Z" name="My test suite" finished-at="2023-05-13T08:37:38Z" duration-ms="20050">
    <groups>
    </groups>
    <test started-at="2023-05-13T08:37:18Z" name="numbersXML" finished-at="2023-05-13T08:37:38Z" duration-ms="20050">
      <class name="testRequests">
        <test-method is-config="true" signature="setup()[pri:0, instance:testRequests@d4342c2]" started-at="2023-05-13T08:37:18Z" name="setup" finished-at="2023-05-13T08:37:25Z" duration-ms="6458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testGet()[pri:0, instance:testRequests@d4342c2]" started-at="2023-05-13T08:37:25Z" name="testGet" finished-at="2023-05-13T08:37:26Z" duration-ms="1608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGet -->
        <test-method signature="testInvalidId()[pri:0, instance:testRequests@d4342c2]" started-at="2023-05-13T08:37:26Z" name="testInvalidId" finished-at="2023-05-13T08:37:28Z" duration-ms="1530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidId -->
        <test-method signature="testLongId()[pri:0, instance:testRequests@d4342c2]" started-at="2023-05-13T08:37:28Z" name="testLongId" finished-at="2023-05-13T08:37:29Z" duration-ms="1504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLongId -->
        <test-method signature="testPut()[pri:0, instance:testRequests@d4342c2]" started-at="2023-05-13T08:37:29Z" name="testPut" finished-at="2023-05-13T08:37:31Z" duration-ms="1644" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPut -->
      </class> <!-- testRequests -->
      <class name="UITest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:UITest@2bbf180e]" started-at="2023-05-13T08:37:31Z" name="setUp" finished-at="2023-05-13T08:37:35Z" duration-ms="4063" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="pageTest()[pri:0, instance:UITest@2bbf180e]" started-at="2023-05-13T08:37:35Z" name="pageTest" finished-at="2023-05-13T08:37:37Z" duration-ms="2398" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at UITest.pageTest(UITest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:UITest@2bbf180e]" started-at="2023-05-13T08:37:37Z" name="tearDown" finished-at="2023-05-13T08:37:38Z" duration-ms="790" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- UITest -->
    </test> <!-- numbersXML -->
  </suite> <!-- My test suite -->
</testng-results>
